# 🔧 Data Preprocessing Pipeline
*Professional Guide to Machine Learning Data Preparation*

---

## 📊 Overview

Data preprocessing is a critical phase in any machine learning project. This pipeline includes data cleaning, handling missing values, encoding categorical variables, feature scaling, and outlier detection. These steps ensure high-quality data input and ultimately lead to optimal model performance.

**Workflow:** Raw Data → Clean Data → Scaled Features → Encoded Variables → Model Ready

---

## Step-by-Step Process

### 🔴 Step 1: Handling Missing Data
**Replace missing values (NaN) with column means using SimpleImputer for numerical features**

```python
# Import SimpleImputer for handling missing values
from sklearn.impute import SimpleImputer

# Create imputer with mean strategy
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

# Fit and transform numerical columns (1 and 2)
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])
```

**Key Points:**
- Applied to numerical columns only
- Uses mean imputation strategy
- Preserves data distribution
- Alternative strategies: median, most_frequent

---

### 🟠 Step 2: Feature Scaling
**Normalize numerical features to 0-1 range using MinMaxScaler to improve model performance**

```python
# Import MinMaxScaler for feature scaling
from sklearn.preprocessing import MinMaxScaler

# Initialize scaler
scaler = MinMaxScaler()

# Scale numerical features to [0,1] range
X[:, 1:3] = scaler.fit_transform(X[:, 1:3])
```

**Key Points:**
- Scales features to [0,1] range
- Prevents feature dominance
- Improves algorithm convergence
- Essential for distance-based algorithms

---

### 🟢 Step 3: Categorical Data Encoding
**Convert categorical variables to numerical format using One-Hot Encoding**

```python
# Import required classes for categorical encoding
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Create column transformer with one-hot encoder
ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(), [0])], 
    remainder='passthrough'
)

# Apply transformation and convert back to numpy array
X = np.array(ct.fit_transform(X))
```

**Key Points:**
- Creates binary columns for each category
- Prevents ordinal assumptions
- Applied to first column (index 0)
- Other columns remain unchanged

---

### 🟣 Step 4: Outlier Detection & Removal
**Identify and filter outliers using the IQR (Interquartile Range) method**

```python
# Calculate quartiles for outlier detection
Q1 = np.percentile(X, 25, axis=0)
Q3 = np.percentile(X, 75, axis=0)
IQR = Q3 - Q1

# Define outlier bounds using 1.5 * IQR rule
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Create mask to filter outliers
mask = ((X >= lower_bound) & (X <= upper_bound)).all(axis=1)

# Apply filter to both features and target
X = X[mask]
y = y[mask]
```

**Key Points:**
- Uses statistical IQR method
- 1.5 * IQR rule for bounds
- Removes extreme values
- Maintains data quality

---

## 🎯 Key Benefits

| Benefit | Description |
|---------|------------|
| **🎯 Efficiency** | Streamlined pipeline for complex data processing |
| **🔍 Accuracy** | Noise reduction and data quality improvement |
| **⚡ Performance** | Optimized data for machine learning algorithms |
| **🛡️ Reliability** | Robust preprocessing for consistent results |

---


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [3]:
# Load the dataset from a CSV file named 'PreprocessData.csv' into a pandas DataFrame
dataset = pd.read_csv('PreprocessData.csv')

# Extract all columns except the last one from the dataset and convert them to a NumPy array, assigning it to X
X = dataset.iloc[:, :-1].values

# Extract the last column from the dataset and convert it to a NumPy array, assigning it to y
y = dataset.iloc[:, -1].values

In [5]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
y

array([2, 5, 1, 0, 7, 8, 9, 1, 5, 6])

## 1. Taking care of missing data

In [6]:
# Import the SimpleImputer class from sklearn to handle missing data
from sklearn.impute import SimpleImputer

# Create an imputer object that will replace missing values (NaN) with the mean of the column
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

# Fit the imputer to the columns 1 and 2 of X to compute the mean of these columns
imputer.fit(X[:, 1:3])

# Transform the columns 1 and 2 of X by replacing missing values with the computed mean
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [7]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

# 2. Feature Scaling

In [10]:
%pip install scikit-learn


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [12]:
from sklearn.preprocessing import MinMaxScaler

# Initialize the MinMaxScaler
scaler = MinMaxScaler()

# Scale only the numerical columns (columns 1 and 2) in X
X[:, 1:3] = scaler.fit_transform(X[:, 1:3])

In [9]:
X

array([['France', 0.7391304347826089, 0.6857142857142855],
       ['Spain', 0.0, 0.0],
       ['Germany', 0.1304347826086958, 0.17142857142857149],
       ['Spain', 0.4782608695652175, 0.37142857142857144],
       ['Germany', 0.5652173913043479, 0.45079365079365075],
       ['France', 0.34782608695652173, 0.2857142857142856],
       ['Spain', 0.5120772946859904, 0.11428571428571432],
       ['France', 0.9130434782608696, 0.8857142857142857],
       ['Germany', 1.0, 1.0],
       ['France', 0.43478260869565233, 0.5428571428571427]], dtype=object)

## 3. Encoding categorical data

### Encoding the Independent Variable

In [15]:
# Import ColumnTransformer from sklearn to apply transformations to specific columns of the data.
from sklearn.compose import ColumnTransformer

# Import OneHotEncoder from sklearn to perform one-hot encoding on categorical data.
from sklearn.preprocessing import OneHotEncoder

# Create a ColumnTransformer object that applies one-hot encoding to the first column (index 0) of X.
# The remainder='passthrough' argument ensures that all other columns remain unchanged.
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')

# Fit the ColumnTransformer to X and transform X, converting the result back into a NumPy array.
X = np.array(ct.fit_transform(X))

In [18]:
print(X)
# Convert the array to a pandas DataFrame with appropriate column names
import pandas as pd

# Create column names based on the data structure
# First 3 columns are one-hot encoded country names, followed by scaled Age and Salary
# Added 'Extra_Column' to match the 6 columns in X
column_names = ['France', 'Germany', 'Spain', 'Age_Scaled', 'Salary_Scaled', 'Extra_Column']

# Convert to DataFrame
df = pd.DataFrame(X, columns=column_names)

# Display the DataFrame
print("\n")
print(df)


[[0.0 1.0 0.0 0.0 0.7391304347826089 0.6857142857142855]
 [1.0 0.0 0.0 1.0 0.0 0.0]
 [1.0 0.0 1.0 0.0 0.1304347826086958 0.17142857142857149]
 [1.0 0.0 0.0 1.0 0.4782608695652175 0.37142857142857144]
 [1.0 0.0 1.0 0.0 0.5652173913043479 0.45079365079365075]
 [0.0 1.0 0.0 0.0 0.34782608695652173 0.2857142857142856]
 [1.0 0.0 0.0 1.0 0.5120772946859904 0.11428571428571432]
 [0.0 1.0 0.0 0.0 0.9130434782608696 0.8857142857142857]
 [1.0 0.0 1.0 0.0 1.0 1.0]
 [0.0 1.0 0.0 0.0 0.43478260869565233 0.5428571428571427]]


  France Germany Spain Age_Scaled Salary_Scaled Extra_Column
0    0.0     1.0   0.0        0.0       0.73913     0.685714
1    1.0     0.0   0.0        1.0           0.0          0.0
2    1.0     0.0   1.0        0.0      0.130435     0.171429
3    1.0     0.0   0.0        1.0      0.478261     0.371429
4    1.0     0.0   1.0        0.0      0.565217     0.450794
5    0.0     1.0   0.0        0.0      0.347826     0.285714
6    1.0     0.0   0.0        1.0      0.512077     0.

### 4. Check and Remove Outliers

In [19]:
# Import the NumPy library for numerical computations.
import numpy as np

# Calculate the first quartile (25th percentile) of each column in X.
# This identifies the lower boundary for potential outliers.
Q1 = np.percentile(X, 25, axis=0)

# Calculate the third quartile (75th percentile) of each column in X.
# This identifies the upper boundary for potential outliers.
Q3 = np.percentile(X, 75, axis=0)

# Compute the interquartile range (IQR) by subtracting Q1 from Q3.
# The IQR measures statistical dispersion and helps in outlier detection.
IQR = Q3 - Q1

# Determine the lower bound for outlier detection by subtracting 1.5 times the IQR from Q1.
# Values below this threshold are considered outliers.
lower_bound = Q1 - 1.5 * IQR

# Determine the upper bound for outlier detection by adding 1.5 times the IQR to Q3.
# Values above this threshold are considered outliers.
upper_bound = Q3 + 1.5 * IQR

# Create a mask to filter out outliers from X.
# Include only rows where all column values are within the lower and upper bounds.
mask = ((X >= lower_bound) & (X <= upper_bound)).all(axis=1)
X = X[mask]

# Filter y to match the length of the filtered X_train.
# This ensures y_train corresponds to the samples in X_train.
y = y[mask]


In [20]:
X

array([[0.0, 1.0, 0.0, 0.0, 0.7391304347826089, 0.6857142857142855],
       [1.0, 0.0, 0.0, 1.0, 0.0, 0.0],
       [1.0, 0.0, 1.0, 0.0, 0.1304347826086958, 0.17142857142857149],
       [1.0, 0.0, 0.0, 1.0, 0.4782608695652175, 0.37142857142857144],
       [1.0, 0.0, 1.0, 0.0, 0.5652173913043479, 0.45079365079365075],
       [0.0, 1.0, 0.0, 0.0, 0.34782608695652173, 0.2857142857142856],
       [1.0, 0.0, 0.0, 1.0, 0.5120772946859904, 0.11428571428571432],
       [0.0, 1.0, 0.0, 0.0, 0.9130434782608696, 0.8857142857142857],
       [1.0, 0.0, 1.0, 0.0, 1.0, 1.0],
       [0.0, 1.0, 0.0, 0.0, 0.43478260869565233, 0.5428571428571427]],
      dtype=object)

In [21]:
y

array([2, 5, 1, 0, 7, 8, 9, 1, 5, 6])